name: Ephemeral Woodpecker macOS Agent

on:
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: macos-latest

    steps:
      - name: Start Ephemeral Woodpecker macOS Agent
        env:
          WOODPECKER_SERVER: ${{ secrets.WOODPECKER_SERVER_HOST }}
          WOODPECKER_AGENT_SECRET: ${{ secrets.WOODPECKER_AGENT_SECRET }}
          WOODPECKER_AGENT_SINGLE_WORKFLOW: "true"
          WOODPECKER_BACKEND: "local" # Chạy trực tiếp trên macOS Host
        run: |
          curl -sL https://github.com/woodpecker-ci/woodpecker/releases/download/v3.17.0/woodpecker-agent_darwin_arm64.tar.gz | tar -xz
          ./woodpecker-agent
